FROM mcr.microsoft.com/vscode/devcontainers/universal:1-linux
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -t agnoster \
    -p git \
    -p dotnet \
